export const SUPABASE_URL = 'YOUR_SUPABASE_URL';
export const SUPABASE_ANON_KEY = 'YOUR_SUPABASE_ANON_KEY';
export const GOOGLE_PLACES_API_KEY = 'YOUR_GOOGLE_PLACES_API_KEY';
export const REVENUECAT_API_KEY = 'YOUR_REVENUECAT_API_KEY';
export const ONESIGNAL_APP_ID = 'YOUR_ONESIGNAL_APP_ID';
